/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Uint128 = string;

export interface CurrentBatchResponse {
  id: number;
  requested_bluna_with_fee: Uint128;
  requested_stluna: Uint128;
  [k: string]: unknown;
}
