/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HumanAddr = string;

export interface InitMsg {
  hub_contract: HumanAddr;
  reward_denom: string;
  [k: string]: unknown;
}
